name: sitesurface_flutter_deploy
description: Deploy you flutter website to github
version: 0.0.1
homepage: https://sitesurface.com
repository: https://github.com/Sitesurface/sitesurface_flutter_deploy
issue_tracker: https://github.com/Sitesurface/sitesurface_flutter_deploy/issues

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  args: ^2.4.1
  flutter:
    sdk: flutter
  yaml: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
flutter:
